apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - feature.yml

secretGenerator:
  - name: github-secret
    options:
      disableNameSuffixHash: true
    literals:
      - github-token=<github_token>
