apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - feature.yml

secretGenerator:
  - name: dockerhub-secret
    options:
      disableNameSuffixHash: true
    literals:
      - dockerhub-token=<dockerhub_token>
