apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - minio.yml

patchesStrategicMerge:
  - spinnaker-config.yml

secretGenerator:
  - name: minio-secret-key
    options:
      disableNameSuffixHash: true
    literals:
      - minioAccessKey=SampleAccessKey1!
